alias ..='cd ..'
alias ...='cd ../..'
alias ls='ls -G'
alias ll='ls -lGa'
alias dir='ls -lGa'
alias gits='git status'
alias gs='git status'
alias gl='git log'
alias ga='git add'
alias gd='git diff'
alias gita='git add'
alias gitc='git commit -m'
alias gitco='git checkout'
alias gpl='git pull'
alias gph='git push'
alias gba='git branch -a'
alias gg='git graph --all'
alias tmp='cd ~/tmp;ls -l'
source /home/vagrant/.asdf/asdf.sh
neofetch
asdf current
aws configure
